### ISSUE TITLE
Unhandled exception .NET System.IO.FileLoadException - app won't run

### ISSUE THREAD

**Issue by stepan-albrecht-adastra** [otykier/TabularEditor#1227]
**Describe the bug**
I can't start the application at all, no explicit error message given, app window will not show at all.

**To Reproduce**
I think this is not reproduceable as it is most likely related to my environment - see additional context.

**Application specifics**
TabularEditor.exe, version: 2.25.8952.22276 portable
Windows 10 enterprise

**Additional context**
I'm running app on virtual machine where I don't have administrative rights. I wasn't able to trace back any changes to the OS except of installation of SSMS to the machine, uninstallation of the app didn't fix it. I was able to find two application error logs in Win event log. They suggest some of the .NET runtime libraries might be missing which is causing unhandled exception and failing to start the app. As our support is very slow to respond and maybe also a bit clueless what to do which is the reason why I beg for help here. 
Would you be able to advise which dll might be missing or how to find out? Or what is the possible remedy - I can imagine reinstalling .NET runtime to newer/other version might help?

Event log error #1:
Log Name:      Application
Source:        .NET Runtime
Date:          03/09/2024 17:02:43
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AWCPCStepaXV674
Description:
Application: TabularEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[], Byte[], System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean, Boolean, System.Security.SecurityContextSource)
   at System.Reflection.Assembly.Load(Byte[])
   at Costura.AssemblyLoader.ReadFromEmbeddedResources(System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Reflection.AssemblyName)
   at Costura.AssemblyLoader.ResolveAssembly(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.IO.FileLoadException
   at TabularEditor.Program.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-03T15:02:43.8887064Z" />
    <EventRecordID>19824</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>AWCPCStepaXV674</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: TabularEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[], Byte[], System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean, Boolean, System.Security.SecurityContextSource)
   at System.Reflection.Assembly.Load(Byte[])
   at Costura.AssemblyLoader.ReadFromEmbeddedResources(System.Collections.Generic.Dictionary`2&lt;System.String,System.String&gt;, System.Collections.Generic.Dictionary`2&lt;System.String,System.String&gt;, System.Reflection.AssemblyName)
   at Costura.AssemblyLoader.ResolveAssembly(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.IO.FileLoadException
   at TabularEditor.Program.Main()

</Data>
  </EventData>
</Event>

Followed by error #2:
Log Name:      Application
Source:        Application Error
Date:          03/09/2024 17:02:44
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AWCPCStepaXV674
Description:
Faulting application name: TabularEditor.exe, version: 2.25.8952.22276, time stamp: 0x6687c969
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4780, time stamp: 0xc4a0381f
Exception code: 0xe0434352
Fault offset: 0x00141072
Faulting process ID: 0x5a78
Faulting application start time: 0x01dafe12543e3cf0
Faulting application path: C:\Users\StepanAlbrecht\Downloads\TabularEditor.2.25.0\TabularEditor.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 4a0ab01c-9335-454e-9678-0d8fe699dc0a
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-03T15:02:44.1542470Z" />
    <EventRecordID>19825</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>AWCPCStepaXV674</Computer>
    <Security />
  </System>
  <EventData>
    <Data>TabularEditor.exe</Data>
    <Data>2.25.8952.22276</Data>
    <Data>6687c969</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.4780</Data>
    <Data>c4a0381f</Data>
    <Data>e0434352</Data>
    <Data>00141072</Data>
    <Data>5a78</Data>
    <Data>01dafe12543e3cf0</Data>
    <Data>C:\Users\StepanAlbrecht\Downloads\TabularEditor.2.25.0\TabularEditor.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>4a0ab01c-9335-454e-9678-0d8fe699dc0a</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by otykier** [comment]
@stepan-albrecht-adastra this issue seems similar to #1175 

Tabular Editor is using [Fody/Costura](https://github.com/Fody/Costura) to embed compressed DLLs as resources, which improves app startup time and produces smaller binaries. Howewer, the WDAC Dynamic Code Security policy seems to take issue with this approach, as users in #1175 are confirming. I wonder if something similar could apply in your case?

**Comment by stepan-albrecht-adastra** [comment]
Hi @otykier that's a good catch - I'm working with the security team to help me check if WDAC is the root cause. Will update this thread once properly tested.

**Comment by otykier** [comment]
I believe this should now finally be fixed in [2.29.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.29.0). Could you test it and let me know? Thanks for your patience.
