### ISSUE TITLE
Error Copying Measure w/ "Shown in Perspective" Property Between Models 

### ISSUE THREAD

**Issue by simonnuss** [otykier/TabularEditor#135]
When I try to copy a measure with a "Shown in Perspective" property in one model to another model that does not have a perspective, I receive the following unhandled exception:

************** Exception Text **************
System.ArgumentException: An object with name 'Everything' does not exist in the collection.
Parameter name: name
   at Microsoft.AnalysisServices.Tabular.NamedMetadataObjectCollection`2.get_Item(String name)
   at TabularEditor.TOMWrapper.PerspectiveCollection.TOM_Get(String name)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.get_Item(String name)
   at TabularEditor.TOMWrapper.GenericIndexer`2.GetObjectFromName(String name)
   at TabularEditor.TOMWrapper.GenericIndexer`2.CopyFrom(IDictionary`2 source)
   at TabularEditor.TOMWrapper.PerspectiveIndexer.CopyFrom(String[] perspectives)
   at TabularEditor.TOMWrapper.AnnotationHelper.LoadPerspectives(ITabularPerspectiveObject obj, Boolean includeChildren)
   at TabularEditor.TOMWrapper.TabularCommonActions.InsertObjects(ObjectJsonContainer objectContainer, ITabularNamedObject destination)
   at TabularEditor.UI.Actions.PasteAction.OnExecute(EventArgs e)
   at Crad.Windows.Forms.Actions.Action.DoExecute()
   at Crad.Windows.Forms.Actions.Action.target_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

Example of a measure being copied that causes an error:
{
  "measures": [
    {
  "name": "Avg Daily Login Time (Agent)",
  "expression": "Measure goes here",
  "formatString": "hh:mm AM/PM",
  "isHidden": true,
  "displayFolder": "Agent Login",
  "annotations": [
    {
      "name": "Format",
      "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortTime\" FormatString=\"hh:mm tt\" /></DateTimes></Format>"
    },
    {
      "name": "TabularEditor_InPerspective",
      "value": "[\"Everything\",\"Agent Only\"]"
    }
  ]
}

**Comment by otykier** [comment]
Great catch, thanks! Does this also happen when not using "Save to Folder" (which adds a special annotation to the object)?
