### ISSUE TITLE
Multiple instances of Tabular Editor being open at once causes error when closing

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#139]
Exception occurs when closing multiple instances at once (see the highlighted screenshot for exactly how I did this):

![image](https://user-images.githubusercontent.com/8462929/37691325-25e31ade-2d05-11e8-96a6-d9ccba289ab5.png)

Also see a screenshot of the error:

![image](https://user-images.githubusercontent.com/8462929/37691338-402f0b50-2d05-11e8-81c9-dd86cce620c3.png)

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\Users\Anthony Flynn\AppData\Local\TabularEditor\RecentFiles.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at TabularEditor.UIServices.RecentFiles.Save()
   at TabularEditor.FormMain.FormMain_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.FormClosingEventHandler.Invoke(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by flynna** [comment]
Accidentally posted without comment (sorry). Closing until I get the necessary screenshots/info.

**Comment by flynna** [comment]
Reopening, now that details are added.

**Comment by otykier** [comment]
Thanks for reporting this. Never considered that multiple instances could be closed at the exact same time - should be an easy fix.
