### ISSUE TITLE
Double clicking DataTable in 1200 Compatibility causes error

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#143]
[Removing everything except the exception, as it is irrelevant]

When you double click a DataTable in a model with 1200 compatibility, then select any other node, an error occurs.

************** Exception Text **************
System.InvalidOperationException: The database compatibility level of 1200 is below the minimal compatability level of 1400 needed for [model 'Model'].[table 'Pipeline']::[DefaultDetailRowsDefinition].
   at Microsoft.AnalysisServices.Tabular.MetadataObject.ValidateCompatLevelRequirement(Int32 compatLevelRequest, String requestingPath)
   at Microsoft.AnalysisServices.Tabular.Table.set_DefaultDetailRowsDefinition(DetailRowsDefinition value)
   at TabularEditor.TOMWrapper.Table.set_DefaultDetailRowsExpression(String value)
   at TabularEditor.TOMWrapper.Table.set_Expression(String value)
   at TabularEditor.TOMWrapper.Utils.DaxDependencyHelper.SetDAX(IDaxDependantObject obj, DAXProperty property, String expression)
   at TabularEditor.UI.UIController.SetText(String value)
   at TabularEditor.UI.UIController.ExpressionEditor_AcceptEdit()
   at TabularEditor.UI.UIController.ExpressionEditor_Preview()
   at TabularEditor.UI.UIController.TreeView_SelectionChanged(Object sender, EventArgs e)
   at Aga.Controls.Tree.TreeViewAdv.OnSelectionChanged()
   at Aga.Controls.Tree.TreeViewAdv.set_SuspendSelectionEvent(Boolean value)
   at Aga.Controls.Tree.NormalInputState.DoMouseOperation(TreeNodeAdvMouseEventArgs args, Boolean focusOnly)
   at Aga.Controls.Tree.NormalInputState.MouseUp(TreeNodeAdvMouseEventArgs args)
   at Aga.Controls.Tree.TreeViewAdv.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[... Trimmed DLL output as irrelevant ...]

**Comment by teasot** [comment]
In order to reproduce:

1. Open, or Create, a 1200 model, with at least one data table
![image](https://user-images.githubusercontent.com/8462929/38724938-08cf7838-3f49-11e8-8ada-c1c6045cd523.png)

2. Click a datatable. Note that no expression appears in the editor. 
![image](https://user-images.githubusercontent.com/8462929/38725046-6509840e-3f49-11e8-9d70-73f8e6d0fdac.png)

3. Double-click the data table. Note that no error has occured, but an equals sign has appeared on the editor (no text present).
![image](https://user-images.githubusercontent.com/8462929/38725075-81d48e08-3f49-11e8-9283-f730b035c66e.png)

4. Click anything else. The error occurs.

![image](https://user-images.githubusercontent.com/8462929/38725093-92a9e93a-3f49-11e8-8c4f-f4c135959453.png)

I will dig into the code and try to find what is causing the error.

On a secondary note, I am new to github - is it considered bad form to raise/comment on so many issues in a short period of time? 

Thanks.

**Comment by teasot** [comment]
Duplicate of previous issue 141

**Comment by otykier** [comment]
@teasot - regarding your last question: I don't know what the general gist is on GitHub, but personally I am thrilled that you're taking your time to help me improve Tabular Editor - so please keep it up :-)

On to the issue - your repro steps was exactly what I needed to nail down the issue. I have a fix in the making - stay tuned!
