### ISSUE TITLE
Duplicating Role Causes Exception

### ISSUE THREAD

**Issue by dmgdotnet** [otykier/TabularEditor#151]
System.ArgumentException: This object does not support translations
Parameter name: includeTranslations
   at TabularEditor.TOMWrapper.ModelRole.TabularEditor.TOMWrapper.IClonableObject.Clone(String newName, Boolean includeTranslations, TabularNamedObject newParent)
   at TabularEditor.UI.Actions.ModelActionManager.<>c.<CreateStandardActions>b__8_108(ITabularNamedObject i)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at TabularEditor.UI.Actions.ModelActionManager.<>c.<CreateStandardActions>b__8_107(UITreeSelection s, Model m)
   at TabularEditor.UI.Actions.Action.InternalExecute(Object arg, IEnumerable`1 alternateSelection)
   at TabularEditor.UI.Actions.Action.Execute(Object arg)
   at TabularEditor.UI.UIController.ContextMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Let me know if you need more detail

**Comment by otykier** [comment]
Thanks for posting this. Does it work if you leave the “include translations” check box unchecked?

**Comment by dmgdotnet** [comment]
I disabled that checkbox in the options and it still seems to throw the same error.

**Comment by otykier** [comment]
Can you use copy-paste (CTRL+C CTRL+V) as a workaround?

**Comment by dmgdotnet** [comment]
Yeah that works, thanks
