### ISSUE TITLE
Adding a data column, hierarchy, calculated column, or measure, to more than one table at once causes an exception

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#152]
Selecting two tables, right clicking, then attempting to add a data column, causes an exception.

Will add steps to reproduce.

**Comment by teasot** [comment]
Step 1:

Create an new 1200 model with a single datasource, then add 2 DataTables.

Step 2:

Right click the two tables and select "Create New > Data Column"
OR  "Create New > Hierarchy"
OR  "Create New > Measure"
OR  "Create New > Calculated Column"

![image](https://user-images.githubusercontent.com/8462929/39100907-0d014a7e-46d5-11e8-8ffa-3e65baaef9b2.png)

Step 3:

An exception occurs:

![image](https://user-images.githubusercontent.com/8462929/39100912-2da832ba-46d5-11e8-9e72-8ad4bc787a2a.png)

The exception details are below (for the data column):

************** Exception Text **************
System.Exception: The selection contains more than one object of type Table
   at TabularEditor.UI.UITreeSelection.One[T]()
   at TabularEditor.UI.UITreeSelection.get_Table()
   at TabularEditor.UI.Actions.ModelActionManager.<>c.<CreateStandardActions>b__8_13(UITreeSelection s, Model m)
   at TabularEditor.UI.Actions.Action.InternalExecute(Object arg, IEnumerable`1 alternateSelection)
   at TabularEditor.UI.Actions.Action.Execute(Object arg)
   at TabularEditor.UI.UIController.ContextMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
