### ISSUE TITLE
Cannot load model created with Tabular Editor in SSDT

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#164]
Hi

I developed a model in Tabular editor now i want to change it in SSDT, 
I create new project is SSDT and I choose "Import From Server" then I choose my database it works properly but when i want to open BIM file , an error occurred. I tried many times but the same error occurred!
![untitled222](https://user-images.githubusercontent.com/24508605/41085393-2a65ea76-6a4c-11e8-843d-204726f64ae2.png)

**Comment by otykier** [comment]
Hi Arman,
What happens if you replace the Model.bim file of your SSDT project, with the Model.bim file you can get from saving the model as a file in Tabular Editor?

**Comment by ArmanFalah** [comment]
I tried that too!
Same Error
"============================
Error Message:
============================

An error occurred while opening the model on the workspace database. Reason: Must specify valid information for parsing in the string.

============================
Call Stack:
============================

   at Microsoft.AnalysisServices.VSHost.VSHostManager.PrepareSandbox(Boolean newProject, Boolean& isRefreshNeeded, Boolean& isImpersonationChanged, Boolean& saveRequired, List`1& truncatedTables, Boolean isRealTimeMode, Int32 clientCompatibilityLevel)
   at Microsoft.AnalysisServices.VSHost.Integration.EditorFactory.CreateEditorInstance(UInt32 grfCreateDoc, String pszMkDocument, String pszPhysicalView, IVsHierarchy pvHier, UInt32 itemid, IntPtr punkDocDataExisting, IntPtr& ppunkDocView, IntPtr& ppunkDocData, String& pbstrEditorCaption, Guid& pguidCmdUI, Int32& pgrfCDW)

============================"

**Comment by otykier** [comment]
Hi Arman,
It seems that SSDT is adding some additional annotations, etc., which are not being added to the Model.bim file, when it is originally created with Tabular Editor. Specifically, there's an annotation on the Model object (ClientCompatibilityLevel), and an "id" property at the bottom, which are not added when using Tabular Editor to create the file. Also, the "name" property would be different in versions of Tabular Editor before 2.8.1.

Could you try to manually add the missing annotation and id-property to your Model.bim file, and see if that allows you to load it from SSDT? Thanks!

```json
{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    ...
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}
```

**Comment by otykier** [comment]
Cleaning up old issues with no activity for 1+ year
