### ISSUE TITLE
Unhandled exception when deleting a table

### ISSUE THREAD

**Issue by wenihal** [otykier/TabularEditor#267]
When deleting existing table from model unhandled exception is occurring:

System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.TOMWrapper.Column.get_UsedInRelationships()
   at TabularEditor.TOMWrapper.Column.DeleteLinkedObjects(Boolean isChildOfDeleted)
   at TabularEditor.TOMWrapper.TabularNamedObject.DeleteLinkedObjects(Boolean isChildOfDeleted)
   at TabularEditor.TOMWrapper.Table.DeleteLinkedObjects(Boolean isChildOfDeleted)
   at TabularEditor.TOMWrapper.TabularNamedObject.InternalDelete()
   at TabularEditor.TOMWrapper.TabularNamedObject.Delete()
   at TabularEditor.UI.UISelectionList`1.<>c.<Delete>b__42_1(T i)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at TabularEditor.UI.UISelectionList`1.Delete()
   at TabularEditor.UI.Actions.ModelActionManager.<>c.<CreateStandardActions>b__11_130(UITreeSelection s, Model m)
   at TabularEditor.UI.Actions.Action.InternalExecute(Object arg, IEnumerable`1 alternateSelection)
   at TabularEditor.UI.Actions.Action.Execute(Object arg)
   at TabularEditor.UI.UIController.ContextMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by otykier** [comment]
[Release 2.8.1](https://github.com/otykier/TabularEditor/releases/tag/2.8.1) updated to fix this issue. Thanks for reporting it!
