### ISSUE TITLE
enable XMLA read/write Power BI Desktop

### ISSUE THREAD

**Issue by Tiljander** [otykier/TabularEditor#416]
Hi,

Thanks for a great editor, very appreciated!

Microsoft just announced XMLA read-write in Power BI Premium:
https://powerbi.microsoft.com/en-us/blog/announcing-read-write-xmla-endpoints-in-power-bi-premium-public-preview/

To enable read/write on Power BI Desktop files, the preview feature "Store datasets using enhanced metadata format.":
https://docs.microsoft.com/en-gb/power-bi/desktop-enhanced-dataset-metadata

I enabled this feature, but when I connect to Power BI Desktop I get this message:
![image](https://user-images.githubusercontent.com/35637838/77859608-a8799080-720a-11ea-82ce-31949d80d31c.png)

When adding a calculation group there is no error message, but when trying to add a "new calculation item" I get this error message:
************** Exception Text **************
System.InvalidOperationException: Adding a Calculation Item to a Power BI Data Model is not allowed.
   at TabularEditor.TOMWrapper.CalculationItem.CreateNew(CalculationGroup parent, String name)
   at TabularEditor.TOMWrapper.CalculationGroupTable.AddCalculationItem(String name, String expression)
   at TabularEditor.UI.Actions.ModelActionManager.<>c.<CreateStandardActions>b__11_19(UITreeSelection s, Model m)
   at TabularEditor.UI.Actions.Action.InternalExecute(Object arg, IEnumerable`1 alternateSelection)
   at TabularEditor.UI.Actions.Action.Execute(Object arg)
   at TabularEditor.UI.UIController.ContextMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**If this feature is enabled, I would be super grateful!**

**Again, thank you for a great editor!**

**Comment by otykier** [comment]
PBI Desktop doesn’t support external tools *yet*, even if you enable enhanced metadata, so the warning provided by Tabular Editor is correct.

However, you can still allow Tabular Editor to make any change by going to File > Preferences and putting a checkbox in “Allow experimental Power BI Features”.

But again - keep in mind that this is still not supported by Microsoft, so if something breaks you shouldn’t expect that Microsoft Support can assist you. Keep a backup of your .pbix just in case. Christian Wade mentioned that this will be supported later this year, however.

**Comment by otykier** [comment]
Latest version [2.9.6](https://github.com/otykier/TabularEditor/releases/tag/2.9.6) should now provide a more descriptive warning message. The UI should no longer crash when you add a calc group:
- For Power BI models that do not use the Enhanced Model Metadata format, the UI will be in "read-only mode" unless you allow experimental Power BI features.
- For Power BI models that do use the Enhanced Model Metadata format, the UI will allow certain, limited changes, such as adding calculation groups, measures, etc.
- With Experimental Power BI Features enabled, you can make any change, but this is, of course, at your own risk. The UI will show a warning in this case.
