### ISSUE TITLE
Crashes when Saving to folder with special characters in file name (:)

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#44]
Hi,

we have Dimension Attributes Named "Cost Center: Responsible" in our model. Saving this to a folder crashes the Tabular Editor:

````
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at TabularEditor.TOMWrapper.TabularModelHandler.OutArray(String path, String arrayName, JArray array)
   at TabularEditor.TOMWrapper.TabularModelHandler.SaveToFolder(String path)
   at TabularEditor.UI.UIController.File_SaveToFolder()
   at TabularEditor.FormMain.saveToFolderToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

Thanks for the great tool.

Felix

**Comment by otykier** [comment]
Hi Felix, thank you for the feedback.

This turned out to be a simple issue of filenames not being properly sanitized in the SaveToFolder() method. It's been fixed in the [latest release](https://github.com/otykier/TabularEditor/releases/latest).
