### ISSUE TITLE
Tabular Editors object explorer crashes when trying to expand the partition list

### ISSUE THREAD

**Issue by savoy9** [otykier/TabularEditor#576]
I'm connected to a PBI premium model. The error occurs when expanding tables with multiple partitions but not when expanding single partition tables. After the crash the object explorer UI has a big red X in it, but the other elements seem to work normally.
I'm running version 2.11.7517.20764

![image](https://user-images.githubusercontent.com/41710547/90797810-fc723800-e2c5-11ea-83db-001b639eded5.png)

Exception Text:
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.FormMain.nodeTextBox5_ValueNeeded(Object sender, NodeControlValueEventArgs e)
   at Aga.Controls.Tree.NodeControls.BindableControl.OnValueNeeded(NodeControlValueEventArgs args)
   at Aga.Controls.Tree.NodeControls.BindableControl.GetValue(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.GetLabel(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.MeasureSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.NodeControls.NodeControl.GetActualSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__114.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__113.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.DrawNode(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.DrawRow(PaintEventArgs e, DrawContext& context, Int32 row, Rectangle rowRect)
   at Aga.Controls.Tree.TreeViewAdv.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

full error message attached:
[TE error message.txt](https://github.com/otykier/TabularEditor/files/5104187/TE.error.message.txt)

**Comment by rednax1994** [comment]
I'm experiencing the same thing, when connecting to a tabular model on Azure Analysis Services.
For me it happens when expanding the Tables tab, while the other ones are fine. 

The error code for me is:
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.FormMain.nodeTextBox5_ValueNeeded(Object sender, NodeControlValueEventArgs e)
   at Aga.Controls.Tree.NodeControls.BindableControl.OnValueNeeded(NodeControlValueEventArgs args)
   at Aga.Controls.Tree.NodeControls.BindableControl.GetValue(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.GetLabel(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.MeasureSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.NodeControls.NodeControl.GetActualSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__114.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__113.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.DrawNode(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.DrawRow(PaintEventArgs e, DrawContext& context, Int32 row, Rectangle rowRect)
   at Aga.Controls.Tree.TreeViewAdv.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by otykier** [comment]
Thanks for reporting. Would it be possible for either of you to share the Model.bim file that's causing this? If so, please send it to do@kapacity.dk

**Comment by otykier** [comment]
Please disregard previous message. I located the issue and will release an updated version with a fix shortly.

**Comment by otykier** [comment]
Fixed in [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0).
