### ISSUE TITLE
Best Practice Analyzer - Unhandled exception is crashing TE

### ISSUE THREAD

**Issue by FrankPreusker** [otykier/TabularEditor#767]
TE version 2.14.1

Steps to reproduce:
1. Open TE from PBI Desktop. Open & run Best Practice Analyzer
2. Delete a calculated column in PBI Desktop, which was marked by an exception rule in the Best Practice Analyzer
3. Error: Unhandled exception

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.TOMWrapper.Column.get_DaxObjectFullName()
   at TabularEditor.BestPracticeAnalyzer.AnalyzerResult.get_ObjectName()
   at TabularEditor.UI.Dialogs.BPAForm.txtObjectName_ValueNeeded(Object sender, NodeControlValueEventArgs e)
   at Aga.Controls.Tree.NodeControls.BindableControl.OnValueNeeded(NodeControlValueEventArgs args)
   at Aga.Controls.Tree.NodeControls.BindableControl.GetValue(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.GetLabel(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.MeasureSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.NodeControls.NodeControl.GetActualSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__114.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__113.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.GetNodeControlInfoAt(TreeNodeAdv node, Point point)
   at Aga.Controls.Tree.TreeViewAdv.GetNodeControlInfoAt(Point point)
   at Aga.Controls.Tree.TreeViewAdv.CreateMouseArgs(MouseEventArgs e)
   at Aga.Controls.Tree.TreeViewAdv.DisplayNodesTooltip(MouseEventArgs e)
   at Aga.Controls.Tree.TreeViewAdv.UpdateToolTip(MouseEventArgs e)
   at Aga.Controls.Tree.TreeViewAdv.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by otykier** [comment]
Fixed in [2.14.2](https://github.com/otykier/TabularEditor/releases/latest). Thanks for reporting!
