### ISSUE TITLE
BPA Corrupted my pbix file

### ISSUE THREAD

**Issue by jkenne01** [otykier/TabularEditor#788]
Hi,

I ran the BPA Fixes over the top of my pbix file and uploaded to the service. It still works in the service but I can no longer open the file in the Power BI Desktop. I get the error below:

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.90.782.0","ModuleName":"Microsoft.PowerBI.Client.Windows.dll","Component":"Microsoft.PowerBI.Client.Windows.AnalysisServices.AnalysisServicesService","Error":"Microsoft.PowerBI.Client.Windows.AnalysisServices.XmlaExecutionException - PFE_TM_DETAIL_ROWS_DISABLED","MethodDef":"ExecuteXmla","ErrorOffset":"112"}

InnerException0.Stack Trace Message:
The DetailRowsExpression/DefaultDetailRowsExpression feature is not enabled. The table 'XXXXXXXXXXXXXX' is using one of those properties, but they are reserved for future use.

InnerException0.Stack Trace:

InnerException0.Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo.GetFeedbackValuesFromException(Exception e, String prefix)
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo.GetFeedbackValuesFromInnerExceptions(Exception e, Int32 depth)
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo.CreateAdditionalErrorInfo(Exception e)
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo..ctor(String message, Exception exception, Nullable`1 stackTraceInfo, String messageDetail)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

PowerBINonFatalError_ErrorDescription:
PFE_TM_DETAIL_ROWS_DISABLED

PowerBIUserFeedbackServices_IsReported:
True

**Comment by otykier** [comment]
Looks like you enabled unsupported Power BI features in Tabular Editor, which may cause .pbix corruption. Hopefully you still have a backup of the .pbix file before the BPA changes were applied.

> The DetailRowsExpression/DefaultDetailRowsExpression feature is not enabled. The table 'XXXXXXXXXXXXXX' is using one of those properties, but they are reserved for future use.

This error message indicates that a detail rows expression was applied to one of the tables in the model. I'm curious to know which BPA rule caused this change. Which collection of BPA rules were you using?
